# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2026 Sasha Levin <sashal@kernel.org>

PACKAGE_NAME="killswitch"
PACKAGE_VERSION="0.1"

BUILT_MODULE_NAME[0]="killswitch"
DEST_MODULE_LOCATION[0]="/kernel/extra/killswitch"

BUILT_MODULE_NAME[1]="test_killswitch"
DEST_MODULE_LOCATION[1]="/kernel/extra/killswitch"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"
AUTOINSTALL="yes"
